#ifndef MLIR_C_BEAVER_CAPI_POLICY_H
#define MLIR_C_BEAVER_CAPI_POLICY_H

// Compile-time markers that describe how Beaver exposes MLIR C API functions
// to BEAM. Both Zig's translated-C namespace and the Elixir manifest extractor
// consume these declarations.
typedef enum {
  BeaverCapiPolicyDiagnostics__mlirAttributeParseGet,
  BeaverCapiPolicyDiagnostics__mlirOperationVerify,
  BeaverCapiPolicyDiagnostics__mlirTypeParseGet,
  BeaverCapiPolicyDiagnostics__mlirModuleCreateParse,
  BeaverCapiPolicyDiagnostics__mlirExecutionEngineCreate,
  BeaverCapiPolicyDiagnostics__mlirTransformApplyNamedSequence,

  BeaverCapiPolicyDirtyCPUAndIO__mlirExecutionEngineInvokePacked,
  BeaverCapiPolicyDirtyCPUAndIO__beaverOperationDestroyIterative,

  // MlirLogicalResult is a one-byte struct returned by value. Keep Zig out of
  // its ABI entirely: the public MLIR names are backed by external C++
  // wrappers instead of translated-C inline functions.
  BeaverCapiPolicyNIFAlias__mlirLogicalResultSuccess,
  BeaverCapiPolicyNIFAlias__mlirLogicalResultFailure,
  BeaverCapiPolicyNIFAlias__mlirLogicalResultIsSuccess,
  BeaverCapiPolicyNIFAlias__mlirLogicalResultIsFailure,

  BeaverCapiPolicyManualAdapter__mlirInferShapedTypeOpInterfaceInferReturnTypes,
  BeaverCapiPolicyManualAdapter__mlirInferTypeOpInterfaceInferReturnTypes,
  BeaverCapiPolicyManualAdapter__mlirTransformStateForEachParam,
  BeaverCapiPolicyManualAdapter__mlirTransformStateForEachPayloadOp,
  BeaverCapiPolicyManualAdapter__mlirTransformStateForEachPayloadValue,
  BeaverCapiPolicyManualAdapter__beaverMemoryEffectsOpInterfaceGetEffects,
  BeaverCapiPolicyManualAdapter__beaverTranslateModuleToLLVMIRText,
  BeaverCapiPolicyManualAdapter__beaverCompileLLVMIRToPTX,

  BeaverCapiPolicyManualRuntime__mlirValueReplaceUsesWithIf,

  BeaverCapiPolicyCallbackRuntime__mlirTypeConverterAddConversion,
  BeaverCapiPolicyCallbackRuntime__mlirTypeConverterAdd1ToNConversion,
  BeaverCapiPolicyCallbackRuntime__mlirTypeConverterAddSourceMaterialization,
  BeaverCapiPolicyCallbackRuntime__mlirTypeConverterAddTargetMaterialization,
  BeaverCapiPolicyCallbackRuntime__mlirTypeConverterAdd1ToNTargetMaterialization,
  BeaverCapiPolicyCallbackRuntime__mlirConversionTargetAddDynamicallyLegalOp,
  BeaverCapiPolicyCallbackRuntime__mlirConversionTargetAddDynamicallyLegalDialect,
  BeaverCapiPolicyCallbackRuntime__mlirConversionTargetMarkOpRecursivelyLegal,
  BeaverCapiPolicyCallbackRuntime__mlirConversionTargetMarkUnknownOpDynamicallyLegal,
  BeaverCapiPolicyCallbackRuntime__mlirOpConversionPatternCreate,
  BeaverCapiPolicyCallbackRuntime__mlirConditionallySpeculatableOpInterfaceAttachFallbackModel,
  BeaverCapiPolicyCallbackRuntime__beaverMemoryEffectsOpInterfaceAttachFallbackModel,
  BeaverCapiPolicyCallbackRuntime__mlirPatternDescriptorOpInterfaceAttachFallbackModel,
  BeaverCapiPolicyCallbackRuntime__mlirTransformOpInterfaceAttachFallbackModel,
  BeaverCapiPolicyCallbackRuntime__mlirDynamicOpTraitCreate,

  // Beaver owns a stable adapter for the MemoryEffects collector ABI. Exclude
  // both generations of the upstream surface so manifests remain identical
  // when compiling against Triton LLVM or an LLVM-main eudsl snapshot.
  BeaverCapiPolicyExclude__mlirMemoryEffectsOpInterfaceAttachFallbackModel,
  BeaverCapiPolicyExclude__mlirMemoryEffectsOpInterfaceGetEffects,
  BeaverCapiPolicyExclude__mlirMemoryEffectInstancesListAppend,
  BeaverCapiPolicyExclude__mlirTransformOnlyReadsHandle,
  BeaverCapiPolicyExclude__mlirTransformConsumesHandle,
  BeaverCapiPolicyExclude__mlirTransformProducesHandle,
  BeaverCapiPolicyExclude__mlirTransformModifiesPayload,
  BeaverCapiPolicyExclude__mlirTransformOnlyReadsPayload,
} BeaverCapiPolicyMarker;

#endif // MLIR_C_BEAVER_CAPI_POLICY_H
