defmodule Beaver.Pattern.Native.Descriptor do
  @moduledoc """
  A native rewrite declaration ready to be added to an MLIR rewrite pattern set.

  Build descriptors with a function generated by
  `Beaver.Pattern.Native.defrewrite/3` rather than constructing this struct
  directly.
  """

  @enforce_keys [:name, :root, :match_and_rewrite]
  defstruct [
    :name,
    :root,
    :match_and_rewrite,
    benefit: 1,
    init_state: nil,
    construct: &Beaver.FallbackPattern.construct/1,
    destruct: &Beaver.FallbackPattern.destruct/1
  ]

  @type outcome(state) :: {:ok, state} | {:error, state}
  @type callback(state) ::
          (Beaver.MLIR.RewritePattern.t(),
           Beaver.MLIR.Operation.t(),
           Beaver.MLIR.PatternRewriter.t(),
           state ->
             outcome(state))

  @type t(state) :: %__MODULE__{
          name: atom(),
          root: String.t(),
          match_and_rewrite: callback(state),
          benefit: non_neg_integer(),
          init_state: state,
          construct: (state -> state),
          destruct: (state -> any())
        }

  @type t() :: t(any())
end

defmodule Beaver.Pattern.Native do
  @moduledoc """
  An explicitly callback-backed rewrite DSL.

  `defrewrite/3` binds selected pieces of an operation before running an
  Elixir callback through `Beaver.MLIR.RewritePattern`. It does not build PDL
  and never switches between the native and PDL execution engines.

  A declaration generates a zero- and one-arity builder. For example,
  `fold_add/0` returns a `Beaver.Pattern.Native.Descriptor`, while
  `fold_add/1` can override lifecycle options such as `:benefit` and
  `:init_state`.
  """

  alias Beaver.MLIR.Operation
  alias Beaver.Pattern.Native.Descriptor
  alias Beaver.Walker

  @declaration_options [
    :root,
    :operands,
    :results,
    :attributes,
    :benefit,
    :init_state,
    :construct,
    :destruct
  ]
  @builder_options [:root, :benefit, :init_state, :construct, :destruct]

  defmacro __using__(_opts) do
    quote do
      import Beaver.Pattern.Native, only: [defrewrite: 2, defrewrite: 3]
    end
  end

  @doc """
  Defines a native rewrite and generates a descriptor builder.

  The declaration must name the callback's operation, borrowed pattern
  rewriter, and state arguments with three variables. Destructure state inside
  the body when needed. `:root` is required. Optional `:operands`, `:results`,
  and `:attributes` declarations are Elixir patterns; a mismatch returns
  no-match without evaluating the body.

  The body may return `:ok`, `:no_match`, `{:ok, new_state}`, or
  `{:error, new_state}`.
  """
  defmacro defrewrite(call, opts_or_block, block \\ nil) do
    declaration = merge_declaration!(opts_or_block, block)
    {name, operation_variable, rewriter_variable, state_variable} = decompose_call!(call)

    validate_keyword!(declaration, [:do | @declaration_options], "defrewrite declaration")
    {body, declaration} = Keyword.pop!(declaration, :do)

    unless Keyword.has_key?(declaration, :root) do
      raise ArgumentError, "defrewrite requires the :root option"
    end

    {operands_pattern, declaration} = Keyword.pop(declaration, :operands)
    {results_pattern, declaration} = Keyword.pop(declaration, :results)
    {attributes_pattern, declaration} = Keyword.pop(declaration, :attributes)

    validate_list_pattern!(:operands, operands_pattern)
    validate_list_pattern!(:results, results_pattern)
    attribute_pairs = validate_attributes_pattern!(attributes_pattern)

    callback_operation = Macro.unique_var(:native_operation, __MODULE__)
    callback_rewriter = Macro.unique_var(:native_rewriter, __MODULE__)
    callback_state = Macro.unique_var(:native_state, __MODULE__)

    match_body =
      build_match_body(
        callback_operation,
        callback_state,
        operands_pattern,
        results_pattern,
        attribute_pairs,
        body,
        name
      )

    callback_body =
      quote do
        unquote(operation_variable) = unquote(callback_operation)
        unquote(rewriter_variable) = unquote(callback_rewriter)
        unquote(state_variable) = unquote(callback_state)
        unquote(match_body)
      end

    declaration_ast = Enum.map(declaration, fn {key, value} -> {key, value} end)
    callback_pattern = Macro.unique_var(:_native_pattern, __MODULE__)
    native_module = __MODULE__

    quote do
      def unquote(name)(opts \\ []) do
        unquote(native_module).build_descriptor(
          unquote(name),
          [unquote_splicing(declaration_ast)],
          fn unquote(callback_pattern),
             unquote(callback_operation),
             unquote(callback_rewriter),
             unquote(callback_state) ->
            unquote(callback_body)
          end,
          opts
        )
      end
    end
  end

  @doc false
  @spec build_descriptor(atom(), keyword(), Descriptor.callback(any()), keyword()) ::
          Descriptor.t()
  def build_descriptor(name, declared_opts, match_and_rewrite, runtime_opts)
      when is_atom(name) and is_function(match_and_rewrite, 4) do
    validate_keyword!(declared_opts, @builder_options, "defrewrite options")
    validate_keyword!(runtime_opts, @builder_options, "native rewrite builder options")

    opts = Keyword.merge(declared_opts, runtime_opts)
    root = opts |> Keyword.fetch!(:root) |> normalize_root!()
    benefit = Keyword.get(opts, :benefit, 1)
    construct = Keyword.get(opts, :construct, &Beaver.FallbackPattern.construct/1)
    destruct = Keyword.get(opts, :destruct, &Beaver.FallbackPattern.destruct/1)

    unless is_integer(benefit) and benefit >= 0 do
      raise ArgumentError, "native rewrite :benefit must be a non-negative integer"
    end

    unless is_function(construct, 1) do
      raise ArgumentError, "native rewrite :construct must be a function of arity 1"
    end

    unless is_function(destruct, 1) do
      raise ArgumentError, "native rewrite :destruct must be a function of arity 1"
    end

    %Descriptor{
      name: name,
      root: root,
      match_and_rewrite: match_and_rewrite,
      benefit: benefit,
      init_state: Keyword.get(opts, :init_state),
      construct: construct,
      destruct: destruct
    }
  end

  @doc false
  @spec configure(Descriptor.t(), keyword()) :: Descriptor.t()
  def configure(%Descriptor{} = descriptor, opts) do
    validate_keyword!(opts, @builder_options, "native rewrite descriptor options")

    descriptor
    |> Map.from_struct()
    |> Map.take(@builder_options)
    |> Map.to_list()
    |> then(&build_descriptor(descriptor.name, &1, descriptor.match_and_rewrite, opts))
  end

  @doc false
  @spec normalize_outcome(term(), state, atom()) :: Descriptor.outcome(state) when state: var
  def normalize_outcome(:ok, state, _name), do: {:ok, state}
  def normalize_outcome(:no_match, state, _name), do: {:error, state}
  def normalize_outcome({:ok, new_state}, _state, _name), do: {:ok, new_state}
  def normalize_outcome({:error, new_state}, _state, _name), do: {:error, new_state}

  def normalize_outcome(other, _state, name) do
    raise RuntimeError,
          "unsupported outcome #{inspect(other)} returned by native rewrite pattern #{inspect(name)}"
  end

  @doc false
  @spec invoke_body((-> term()), state, atom()) :: Descriptor.outcome(state) when state: var
  def invoke_body(body, state, name) when is_function(body, 0) do
    body.() |> normalize_outcome(state, name)
  end

  defp merge_declaration!(opts_or_block, nil), do: opts_or_block

  defp merge_declaration!(opts, block) when is_list(opts) and is_list(block) do
    Keyword.merge(opts, block)
  end

  defp merge_declaration!(_opts, _block) do
    raise ArgumentError, "defrewrite expects a keyword declaration followed by a do block"
  end

  defp decompose_call!(call) do
    case Macro.decompose_call(call) do
      {name, [operation, rewriter, state]} when is_atom(name) ->
        Enum.each([operation, rewriter, state], &validate_callback_variable!/1)
        {name, operation, rewriter, state}

      _ ->
        raise ArgumentError,
              "defrewrite expects name(operation, rewriter, state) as its first argument"
    end
  end

  defp validate_callback_variable!({name, _meta, context})
       when is_atom(name) and (is_atom(context) or is_nil(context)),
       do: :ok

  defp validate_callback_variable!(_other) do
    raise ArgumentError,
          "defrewrite callback arguments must be variables; destructure state inside the body"
  end

  defp validate_keyword!(opts, allowed, description) do
    unless Keyword.keyword?(opts) do
      raise ArgumentError, "#{description} must be a keyword list"
    end

    keys = Keyword.keys(opts)

    case keys -- Enum.uniq(keys) do
      [] -> :ok
      duplicates -> raise ArgumentError, "duplicate #{description} keys: #{inspect(duplicates)}"
    end

    case keys -- allowed do
      [] ->
        opts

      unsupported ->
        raise ArgumentError, "unsupported #{description} keys: #{inspect(unsupported)}"
    end
  end

  defp validate_list_pattern!(_name, nil), do: :ok
  defp validate_list_pattern!(_name, pattern) when is_list(pattern), do: :ok

  defp validate_list_pattern!(name, _pattern) do
    raise ArgumentError, "defrewrite :#{name} must be a literal list pattern"
  end

  defp validate_attributes_pattern!(nil), do: []

  defp validate_attributes_pattern!(pairs) when is_list(pairs) do
    unless Enum.all?(pairs, fn
             {name, _pattern} when is_atom(name) or is_binary(name) -> true
             _ -> false
           end) do
      raise ArgumentError,
            "defrewrite :attributes must be a list of {literal_name, pattern} pairs"
    end

    names = Enum.map(pairs, &elem(&1, 0))

    if length(names) != length(Enum.uniq(names)) do
      raise ArgumentError, "defrewrite :attributes contains duplicate names"
    end

    pairs
  end

  defp validate_attributes_pattern!(_other) do
    raise ArgumentError,
          "defrewrite :attributes must be a list of {literal_name, pattern} pairs"
  end

  defp normalize_root!(root) when is_function(root, 0), do: root.() |> normalize_root!()
  defp normalize_root!(root) when is_atom(root), do: root |> Atom.to_string() |> normalize_root!()
  defp normalize_root!(root) when is_binary(root) and root != "", do: root

  defp normalize_root!(_root) do
    raise ArgumentError, "native rewrite :root must resolve to a non-empty operation name"
  end

  defp build_match_body(
         operation,
         state,
         operands_pattern,
         results_pattern,
         attribute_pairs,
         body,
         name
       ) do
    native_module = __MODULE__

    normalized_body =
      quote do
        unquote(native_module).invoke_body(
          fn -> unquote(body) end,
          unquote(state),
          unquote(name)
        )
      end

    attributes_matched =
      build_attributes_match(operation, state, attribute_pairs, normalized_body)

    results_matched =
      build_list_match(
        results_pattern,
        quote(do: Operation.results(unquote(operation)) |> Enum.to_list()),
        state,
        attributes_matched
      )

    build_list_match(
      operands_pattern,
      quote(do: Walker.operands(unquote(operation)) |> Enum.to_list()),
      state,
      results_matched
    )
  end

  defp build_list_match(nil, _values, _state, inner), do: inner

  defp build_list_match(pattern, values, state, inner) do
    quote do
      case unquote(values) do
        unquote(pattern) -> unquote(inner)
        _ -> {:error, unquote(state)}
      end
    end
  end

  defp build_attributes_match(_operation, _state, [], inner), do: inner

  defp build_attributes_match(operation, state, pairs, inner) do
    Enum.reduce(Enum.reverse(pairs), inner, fn {attribute_name, pattern}, acc ->
      quote do
        case Operation.fetch(unquote(operation), unquote(to_string(attribute_name))) do
          {:ok, unquote(pattern)} -> unquote(acc)
          :error -> {:error, unquote(state)}
        end
      end
    end)
  end
end
