name: Elixir CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.13.0" # Define the elixir version [required]
          otp-version: "24.1" # Define the OTP version [required]
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Download pre-build LLVM
        run: |
          wget https://github.com/MLIR-China/stage/releases/download/nightly-tag-2022-08-10-0737/llvm-install.zip
          unzip llvm-install.zip -d $HOME/llvm-install
      - name: Run smoke tests
        env:
          LLVM_CONFIG_PATH: "/home/runner/llvm-install/bin/llvm-config"
        run: |
          mix test --only smoke
      - name: Run tests
        env:
          LLVM_CONFIG_PATH: "/home/runner/llvm-install/bin/llvm-config"
        run: |
          mix test --exclude vulkan --exclude todo
