name: Elixir CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true
env:
  LLVM_CONFIG_PATH: "/home/runner/llvm-install/bin/llvm-config"
jobs:
  build:
    name: Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["25.0"]
        elixir: ["1.13.0"]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Download pre-build LLVM
        run: |
          wget --progress=bar:force:noscroll https://github.com/MLIR-China/stage/releases/download/llvm-commit-1d31ea68c0cbc24d690a58c296b50b61595b6127-2022-10-25-0120/llvm-install-x86_64-unknown-linux-gnu-MinSizeRel.zip -O llvm-install.zip
          unzip llvm-install.zip -d $HOME/llvm-install
      - name: Run smoke tests
        run: |
          mix test --force --only smoke
      - name: Run tests
        run: |
          mix test --exclude vulkan --exclude todo
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: beaver-tmp-${{ github.run_number }}-${{ github.run_attempt }}
          path: ./tmp/**/*.zig
