defmodule Beaver.Data do
  @moduledoc """
  This module provide higher level interface to primitive data types and MemRefDescriptor C struct in [MemRef](https://mlir.llvm.org/docs/Dialects/MemRef/) dialect.
  It aims to manage memory with BEAM utility like ets and help a Erlang/Elixir function play well with function generated by MLIR and other NIFs.
  """
  # TODO: move modules like CAPI.F32 here
end
